In [ ]:
from google.colab import files
uploaded = files.upload()

Saving uybor.csv to uybor.csv

In [ ]:
import pandas as pd
import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.metrics import mean_squared_error
from sklearn.impute import SimpleImputer

In [ ]:
df = pd.read_csv("uybor.csv")

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 518 entries, 0 to 517
Data columns (total 25 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Unnamed: 0.1        518 non-null    int64
 1   Unnamed: 0          518 non-null    int64
 2   Title               518 non-null    object
 3   Square              518 non-null    object
 4   Price               518 non-null    object
 5   Room                518 non-null    object
 6   Floor               518 non-null    int64
 7   Building floor      518 non-null    int64
 8   Renovation          518 non-null    object
 9   Material            518 non-null    object
 10  Address             518 non-null    object
 11  Lift                518 non-null    int64
 12  Bathroom            518 non-null    int64
 13  Washing machine     518 non-null    int64
 14  TV                  518 non-null    int64
 15  Microwave oven      518 non-null    int64
 16  Playground          518 non-null    int64
 17  Furniture           518 non-null    int64
 18  Refrigerator        518 non-null    int64
 19  Air conditioner     518 non-null    int64
 20  Wifi                518 non-null    int64
 21  Cable               518 non-null    int64
 22  Security            518 non-null    int64
 23  Video surveillance  518 non-null    int64
 24  Parking space       518 non-null    int64
dtypes: int64(18), object(7)
memory usage: 101.3+ KB

In [ ]:
!pip install torch

Requirement already satisfied: torch in /usr/local/lib/python3.13/dist-packages (2.11.0+cpu)
Requirement already satisfied: filelock in /usr/local/lib/python3.13/dist-packages (from torch) (3.32.5)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.13/dist-packages (from torch) (4.16.0)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.13/dist-packages (from torch) (80.10.2)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.13/dist-packages (from torch) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.13/dist-packages (from torch) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.13/dist-packages (from torch) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.13/dist-packages (from torch) (2025.12.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.13/dist-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.13/dist-packages (from jinja2->torch) (3.0.3)

In [ ]:
df.head()

,Square,Price,Room,Floor,Building floor,Renovation,Material,Address,Lift,Bathroom,...,Microwave oven,Playground,Furniture,Refrigerator,Air conditioner,Wifi,Cable,Security,Video surveillance,Parking space
0,60.08 м²,61000.0,2,2,9,Требует ремонта,Панельный,"город Ташкент, Яшнободский район, махаллинский...",1,0,...,0,0,0,0,0,0,0,0,0,0
1,95 м²,80000.0,4,5,9,Евроремонт,Панельный,"город Ташкент, Сергелийский район, махаллински...",1,1,...,0,1,1,0,1,1,1,0,0,1
2,37.9 м²,55000.0,1,8,9,Евроремонт,Другое,"город Ташкент, Яшнободский район, жилой компле...",1,0,...,0,1,1,1,0,1,1,1,1,1
3,37 м²,66000.0,1,2,5,Евроремонт,Кирпичный,"город Ташкент, Чиланзарский район, квартал Е, ...",0,0,...,0,0,0,0,0,0,0,0,0,0
4,127 м²,206000.0,4,2,5,Средний,Кирпичный,"город Ташкент, Яшнободский район, махаллинский...",0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
df.drop(['Title','Unnamed: 0.1','Unnamed: 0'], axis=1, inplace=True)

KeyError: "['Title', 'Unnamed: 0.1', 'Unnamed: 0'] not found in axis"

In [ ]:
def price(value):
    value = value.replace(' у.е.', '').replace(' ', '')
    return float(value)
df['Price'] = df['Price'].apply(price)

In [ ]:
df['Price'].value_counts()

Price
75000.0     17
85000.0     16
80000.0     14
65000.0     11
105000.0    11
            ..
84999.0      1
72500.0      1
148000.0     1
109000.0     1
83500.0      1
Name: count, Length: 214, dtype: int64

In [ ]:
def size(value):
    value = value.replace('м²', '').replace(' м²', '').replace(' ', '')
    return float(value)
df['Square'] = df['Square'].apply(size)

In [ ]:
df['Square'].value_counts()

Square
50.00     30
60.00     24
30.00     17
65.00     14
70.00     14
          ..
73.30      1
91.00      1
24.45      1
146.00     1
49.00      1
Name: count, Length: 143, dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 518 entries, 0 to 517
Data columns (total 22 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Square              518 non-null    float64
 1   Price               518 non-null    float64
 2   Room                518 non-null    object
 3   Floor               518 non-null    int64
 4   Building floor      518 non-null    int64
 5   Renovation          518 non-null    object
 6   Material            518 non-null    object
 7   Address             518 non-null    object
 8   Lift                518 non-null    int64
 9   Bathroom            518 non-null    int64
 10  Washing machine     518 non-null    int64
 11  TV                  518 non-null    int64
 12  Microwave oven      518 non-null    int64
 13  Playground          518 non-null    int64
 14  Furniture           518 non-null    int64
 15  Refrigerator        518 non-null    int64
 16  Air conditioner     518 non-null    int64
 17  Wifi                518 non-null    int64
 18  Cable               518 non-null    int64
 19  Security            518 non-null    int64
 20  Video surveillance  518 non-null    int64
 21  Parking space       518 non-null    int64
dtypes: float64(2), int64(16), object(4)
memory usage: 89.2+ KB

In [ ]:
def room(value):
    value = value.replace('+', '').strip()
    return int(value)
df['Room'] = df['Room'].apply(room)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 518 entries, 0 to 517
Data columns (total 22 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Square              518 non-null    float64
 1   Price               518 non-null    float64
 2   Room                518 non-null    int64
 3   Floor               518 non-null    int64
 4   Building floor      518 non-null    int64
 5   Renovation          518 non-null    object
 6   Material            518 non-null    object
 7   Address             518 non-null    object
 8   Lift                518 non-null    int64
 9   Bathroom            518 non-null    int64
 10  Washing machine     518 non-null    int64
 11  TV                  518 non-null    int64
 12  Microwave oven      518 non-null    int64
 13  Playground          518 non-null    int64
 14  Furniture           518 non-null    int64
 15  Refrigerator        518 non-null    int64
 16  Air conditioner     518 non-null    int64
 17  Wifi                518 non-null    int64
 18  Cable               518 non-null    int64
 19  Security            518 non-null    int64
 20  Video surveillance  518 non-null    int64
 21  Parking space       518 non-null    int64
dtypes: float64(2), int64(17), object(3)
memory usage: 89.2+ KB

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [ ]:
x = df.drop("Price", axis=1)
y = df['Price']

In [ ]:
numerical_features = df.select_dtypes(include=['int64','float64']).columns
categorical_features = df.select_dtypes(include=['object']).columns

In [ ]:
print(numerical_features)
print(categorical_features)

Index(['Square', 'Price', 'Room', 'Floor', 'Building floor', 'Lift',
       'Bathroom', 'Washing machine', 'TV', 'Microwave oven', 'Playground',
       'Furniture', 'Refrigerator', 'Air conditioner', 'Wifi', 'Cable',
       'Security', 'Video surveillance', 'Parking space'],
      dtype='object')
Index(['Renovation', 'Material', 'Address'], dtype='object')

In [ ]:
sc = StandardScaler()
oe = OneHotEncoder(drop='first', sparse_output=False, handle_unknown='ignore')
num_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='mean')),
    ('scaler', sc)
 ]
)
cat_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('onehot', oe)
])

In [ ]:
preprocessor = ColumnTransformer(transformers=[
    ('num', num_transformer, numerical_features),
    ('cat', cat_transformer, categorical_features)
])

In [ ]:
x_train_preprocessed = preprocessor.fit_transform(x_train)
y_train_preprocessed = np.log1p(y_train)
x_test_preprocessed = preprocessor.transform(x_test)
y_test_preprocessed = np.log1p(y_test.values)

ValueError: A given column is not a column of the dataframe